spring.config.activate.on-profile=prod

logging.level.root=WARN
logging.level.com.example.ticketsystem=INFO
logging.level.org.springframework.security=WARN

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.error.include-message=never
server.error.include-stacktrace=never
