spring.config.activate.on-profile=dev

logging.level.root=INFO
logging.level.com.example.ticketsystem=DEBUG
logging.level.org.springframework.security=INFO

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
